### EDA&STATS Notebook Week-1

### Table of Contents


##### 1. Exploratory Data Analysis
##### 2. Types of Variables 
##### 3. Population and Sample
##### 4. Descriptive Statistics 
##### 5. Types of Distribution 
##### 6. Visualization Analysis

<a id="eda"></a>
### 1. What is Exploratory Data Analysis?

Exploratory data analysis is an important step in any research analysis. It searches for patterns and relationships in the data. In other words, we may explain EDA as a process to summarise the crucial characteristics of the data to get better insights.<br>
We explore each dataset using multiple techniques and compare the results. We find answers to questions such as:<br>
&nbsp;&nbsp;&nbsp;      1) What is the shape of the data? <br>
&nbsp;&nbsp;&nbsp;      2) Are there redundant variables? <br>
&nbsp;&nbsp;&nbsp;      3) Are there missing or null values? <br>
&nbsp;&nbsp;&nbsp;      4) What is the average value of a feature? <br>
&nbsp;&nbsp;&nbsp;      5) Are there any outliers present? <br>
&nbsp;&nbsp;&nbsp;      6) Is there any relationship between these variables?

**Note:** The questions mentioned above are **not** the only questions answered in EDA. These are a few questions that one may start initially.

<a id="variable"> </a>
### 2 Variables

Identifying the type of variable we are working with is always the first step of the data analysis process. We classify the variables as follows:
<ol>
    <li><b>Numerical (quantitative)</b></li>
    <ul><li>Continuous - A random variable which takes continuous values, i.e. values within a range, usually measured, such as height (within the range of human heights)</li>
        <li>Discrete -  A random variable which takes discrete values, i.e. values from the set of whole numbers only. It can take countably finite values</li></ul><br>
    <li><b>Categorical (qualitative)</b></li>
    <ul>
        <li> Ordinal - Values that have inherent ordering levels, such as (high, medium, low)</li>
        <li>Nominal - Nominal data has no order. The values represent discrete units and are used to label variables (male or female)</li></ul>
</ol>  
Data has categorical and/or numerical variables. The main data types stored in pandas dataframes are object, float, int, boolean and datetime64. It is important to check whether the data types are correctly identified by python.<br>

### 3.What is Population and Sample?
The population is a complete set of elements having some common characteristics selected for a research study.<br>
A sample is a set of randomly chosen observations from a population. Samples are drawn from the population when a dataset is large since it is challenging to study the whole population. We draw a sample when the item under study is feared to exhaust. For instance,<br> 
<ul>
    <li>the study of the durability of an electric bulb </li>
        <li>the study of the effectiveness of new medicine</li>
</ul>

#### Sampling Techniques

#### Sampling without Replacement

In sampling without replacement, once an item is selected, it is not returned to the population before the next selection.
This means each item can be chosen only once.

Example:

Imagine you have 5 colored balls labeled A, B, C, D, E.

If you pick one ball, record it, and then keep it aside/away from the bag and than picking the next — that’s sampling with out replacement.

In [3]:
pop_data = [1,2,3,4,5,6]
n = 4

In [4]:
import random

In [6]:
random.sample(pop_data, n)

[3, 6, 2, 4]

**Note: We can draw defined number of Samples from this method**

#### Sampling with Replacement

In sampling with replacement, after selecting an item from the population, it is returned back before the next selection.
This means the same item can be chosen more than once.

Example:

Imagine you have 5 colored balls labeled A, B, C, D, E.

If you pick one ball, record it, and then put it back into the bag before picking the next — that’s sampling with replacement.

**Note: We can draw infinite number of Samples from this method**

In [14]:
with_replace_data = [1,2,3,4,5,6,7,8,9,10]
k=20
random.choices(with_replace_data, k=k)

[9, 2, 8, 9, 10, 8, 6, 6, 3, 9, 7, 7, 2, 3, 5, 5, 10, 2, 4, 6]

### 4. Descriptive Statistics:

Descriptive statistics summarize a given data set. It includes measures of central tendency, measures of variation and distribution of the data.
<br> The **measures of central tendency** include the mean, median, and mode, while **measures of variability** include the standard deviation, variance, the coefficient of variation, and so on.

### Inferential Statistics:
Inferential statistics are procedures that help in making inferences about a population based on findings from a sample.<br>
It includes **testing of hypothesis** and **parameter estimation**. It allows us to infer parameters of the population based on sample and build models on it.

In [10]:
import pandas as pd

In [12]:
df = pd.read_csv('Updated_Loan.csv')

In [13]:
df.head(5)

,Unnamed: 0,Loan_Status,Applicant_Income,Loan_Amount,Loan_Tenure,Gender,Dependents,Marriage_Status,Occupation,Credit_Score,DOB
0,0,Yes,674507.0,122980,15,Female,Yes,Yes,Business,Medium,1976
1,1,Yes,579260.0,111180,10,NaN,No,Yes,Job,High,1974
2,2,No,697153.0,93364,5,Male,Yes,No,Job,Medium,1990
3,3,Yes,828454.0,188090,5,Female,Yes,Yes,Job,High,1973
4,4,No,564876.0,92806,5,Female,Yes,Yes,Business,Low,1973

In [15]:
import numpy as np

In [18]:
df_num = df.select_dtypes(include = np.number)

In [21]:
df_cat = df.select_dtypes(exclude = np.number)

In [22]:
df_num.describe()

        Unnamed: 0  Applicant_Income   Loan_Amount  Loan_Tenure          DOB
count  1000.000000      8.590000e+02  1.000000e+03  1000.000000  1000.000000
mean    499.500000      6.879275e+05  1.572760e+05    12.725000  1984.988000
std     288.819436      4.663448e+05  2.566797e+05     5.265653     8.998157
min       0.000000      1.954670e+05  2.640100e+04     5.000000  1970.000000
25%     249.750000      5.088370e+05  7.966175e+04    10.000000  1977.000000
50%     499.500000      6.104700e+05  1.037425e+05    15.000000  1985.000000
75%     749.250000      7.085570e+05  1.364740e+05    15.000000  1993.000000
max     999.000000      5.309160e+06  2.551137e+06    25.000000  2000.000000

In [23]:
df_cat.describe()

       Loan_Status Gender Dependents Marriage_Status Occupation Credit_Score
count         1000    801       1000            1000       1000         1000
unique           2      2          2               2          2            3
top            Yes   Male        Yes              No        Job       Medium
freq           500    405        502             502        616          491

<a id="central_tendency"> </a>
####  Measures of Central Tendency

Let us now understand the measures of central tendency.

<a id="mean"></a>
####  Mean
<ul>
  <li>Mean is the average of the data</li>
  <li>The important property of the mean is that it includes all values in the data. Thus it can be affected by the outliers. Presence of outliers can give unreliable results    
</ul>


The answer to the questions above is to find the mean. Let us use the function `.mean()`

In [25]:
df['Applicant_Income'].mean()

np.float64(687927.4586728754)

In [30]:
df[['Applicant_Income', 'Loan_Amount']].median()

Applicant_Income    610470.0
Loan_Amount         103742.5
dtype: float64

In [32]:
df['Occupation'].mode()

0    Job
Name: Occupation, dtype: object

<a id="median"></a>
####  Median
<ul>
  <li>The median value is the middlemost value of the dataset, it divides the data into two equal halves. Thus, it is a positional value</li>
     <li>It cannot be obtained for categorical variables</li>
  <li>Unlike mean, the median value is not affected by extreme values</li>
    <li>The median value is at times used to impute the missing values in the data</li>
</ul>

<a id="mode"></a>
####  Mode
<ul>
  <li> Mode of the data is the value which has the highest frequency</li>
  <li>It is a measure that can be used for categorical variables. Example: gender</li>
</ul>

<a id="dispersion"> </a>
####  Measure of Dispersion
The measure of dispersion indicates the variability within a set of measures, Less variability implies more data is closer to the central observations. More variability implies more data is spread further away from the center

The most popular variability measures are the range, interquartile range (IQR), variance, and standard deviation

<a id="range"> </a>
####  Range
<ul>
  <li>The range represents the difference between the largest and the smallest points in the data</li>
    <li>In spite of being very easy to define and calculate, it is not a reliable measure</li>
    <li>It is highly affected by extreme values</li>
</ul>

In [34]:
range_income = df['Applicant_Income'].max() - df['Applicant_Income'].min()

<a id="iqr"> </a>
#### Interquartile Range (IQR)
<ul>
    <li>The interquartile range is another useful measure of spread based on the quartiles</li>
    <li>It is the difference between the third quartile and the first quartile</li>
    <li>The IQR gives the range of middle 50% of the data</li>
    <li> It also helps in identifying the outliers
    </ul>

In [37]:
Q1 = df['Applicant_Income'].quantile(0.25)
Q3 = df['Applicant_Income'].quantile(0.75)

IQR = Q3 - Q1
print ('IQR', IQR)

IQR 199720.0

<a id="variance"> </a>
#### Variance
<ul>
  <li>Variance measure the dispersion of the data from the mean</li>
  <li>It is an average of the sum of squares of difference between an observation and the mean. Thus the variance is always positive</li>
    <li>It tells us about the squared deviation in the data</li>
</ul>

In [39]:
df['Applicant_Income'].var()

217477446716.12485

<a id="std"> </a>
#### Standard Deviation

<ol>
    <li> Standard deviation is the positive square root of the varianc </li>
    <li> It has the same unit as that of the observations</li>
    <li> Like variance, it also measures the variability of the observations from the mean but its an absolute deviation </li>
    </ol>

In [40]:
df['Applicant_Income'].std()

466344.77236924705

<a id="cv"> </a>
#### Coefficient of Variation
<ul>
    <li>The coefficient of variation is a statistical measure of dispersion of data points around the mean</li>
    <li>It is a unit free measure and is always expressed in percentage</li>
    <li>We compare the coefficient of variation in order to decide which of the two sets of observations has more spread</li>
    <li> CV : (Sigma/mu) * 100
    </ul>

In [2]:
import numpy as np
import pandas as pd

data = {'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],'Oil_USD': [6, 8, 10, 7, 9, 12],'Oil_NGN': [70000, 92000, 90000, 85000, 80000, 75000]}
df = pd.DataFrame(data)

<a id="skewness"> </a>
#### Skewness
<ul>
  <li>Skewness helps us to study the shape of the data.</li>
  <li>It represents how much a distribution differs from a normal distribution, either to the left or to the right.</li>
    <li>The value of the skewness can be either positive, negative or zero.</li>
</ul>

<a id="kurtosis"> </a>
#### Kurtosis
<ul>
    <li> Kurtosis measures the peakedness of the distribution</li>
   <li>In other words, kurtosis is a statistical measure that defines how the tails of the distribution differ from the normal distribution</li>
       <li>Kurtosis identifies whether the tails of a given distribution contain extreme values</li>
</ul>  

To find the kurtosis of the data, we find use the function `kurt()`

<a id="cov"> </a>
#### Covariance

<ul>
  <li>It is the relationship between a pair of random variables where change in one variable causes change in another variable</li>
  <li>It can take any value between -infinity to +infinity, where the negative value represents the negative relationship whereas a positive value represents the positive relationship</li>
</ul>  

</body>
</html>

In [1]:
loan_num = loan.select_dtypes(include=np.number)

<a id="corr"></a>
#### Correlation
  <li>It shows whether pairs of variables are related to each other</li>
  <li>If there is correlation, it shows how strong the correlation is</li>
  <li>Correlation takes values between -1 to +1, where values close to +1 represents strong positive correlation while values close to -1 represents strong negative correlation</li>
</ul>

###

<a id="distribution"> </a>
### 5.Distribution of the data

<ul>
    <li>A distribution in statistics shows how data or values are spread out or how frequently each value occurs in a dataset.
    <li>Think of it as a way of describing the pattern of your data.</li>
    <li>On plotting the histogram or a frequency curve for a variable, we are  actually looking at how the data is distributed over its range</li>

### Types of Distributions:

There are many types, but the most commonly studied are:

Binomial Distribution

Normal Distribution

Standard Normal Distribution

#### Binomial Distribution: 

A Binomial Distribution is used when we perform an experiment that has only two possible outcomes:

#### Properties of Binomial Distribution

There are a fixed number of trials (n).

Each trial has only two possible outcomes (Success or Failure).

The probability of success (p) is the same in each trial.

All trials are independent (the result of one doesn’t affect another).

#### Normal Distribution

A Normal Distribution is a continuous probability distribution where data values are symmetrically distributed around the mean.
It means that most observations are close to the average (mean), its also called as Gaussian Distribution.?

#### Properties of Normal Distribution

The Distribution Follows a Bell Shape Curve. 

The Mean = Median = Mode will be coinciding. 

The data will be symmetric, left side data will be same as right side data.

#### Standard Normal Distribution

A Standard Normal Distribution is a special case of the normal distribution.

It has:  Mean = 0,  Standard Deviation = 1

We convert a normal variable into a standard normal variable using the Z-score.

#### Properties of Standard Normal Distribution

Mean (μ) = 0

Standard Deviation (σ) = 1

Total Area Under the Curve = 1

Empirical Rule Applies (68–95–99.7 rule)

In [3]:
# Generate 1000 random values from a normal distribution
# loc/mean = 50, scale/standard deviation = 10
np.random.seed(42)  # for reproducibility
data = np.random.normal(loc=50, scale=10, size=1000)
data = pd.DataFrame(data,columns=['Price'])

In [5]:
# z_score method to convert Normal Distribution to Standard Normal Distribution

### 6.Visualization Analysis 

Visualization Analysis refers to the process of graphically representing data to understand patterns, trends, and relationships between variables.
It helps in exploring data, identifying insights, and simplifying complex information for better interpretation and decision-making.

Different types of visual analyses are used depending on how many variables are being studied at a time: 

1. Univariate Analysis:

3. Bi_Variate Analysis: 

4. Multivariate Analysis:

#### Univariate Analysis

Univariate Analysis involves the study of a single variable at a time. The main purpose is to describe the data and summarize its pattern using charts or graphs.

Types:

Numerical Data: Use a Histogram to observe the distribution (spread, shape, and central tendency) of values.

Categorical Data: Use a Bar Plot to compare the frequencies or counts of different categories.

#### Numerical Data

#### Categorical Data

### Inference: 

1. There are 2 sub groups (Male & Female) 
2. The mode is Male
3. There is no big imabaance between Male and Female

#### Bivariate Analysis

Bivariate Analysisis the study of the relationship between two variables.It helps to understand how one variable changes with respect to another.

| Variable Type                  | Visualization Tool           | Purpose                                                                    |
| ------------------------------ | ---------------------------- | -------------------------------------------------------------------------- |
| **Numerical vs Numerical**     | **Scatter Plot**             | To check correlation or trend (e.g., height vs. weight)                    |
| **Categorical vs Categorical** | **Grouped / Multi Bar Plot** | To compare category combinations or proportions                            |
| **Numerical vs Categorical**   | **Box Plot / Violin Plot**   | To compare numerical values across categories (e.g., salary by department) |

#### Numeric vs Numeric

#### Categorical vs Categorical

#### Numerical vs Categorical

#### Multivariate Analysis

Multivariate Analysis involves studying two or more variables simultaneously to understand complex relationships between them. It helps to detect interactions, patterns, and influences among multiple factors.

Pair Plot – Shows relationships among multiple numerical variables.

Heatmap – Displays correlation among several variables.