### EDA&STATS Notebook File-2

### Table of Contents


##### 1. Missing Values  
##### 2. Outliers 
##### 3. Encoding
##### 4. Scaling 
##### 5. Transformation
##### 6. Feature Engineering

### Data Processing

Data Processing refers to the systematic steps taken to clean, prepare, and transform raw data into a meaningful and usable format for analysis or modeling.

In real-world datasets, data is often incomplete, inconsistent, or inaccurate — hence we must process it carefully before performing analysis or building models.

#### Data Anomalies

Data Anomalies are problems or irregularities in data that can affect the accuracy and quality of analysis.
Below are the most common types of anomalies and their treatment steps

#####  Spelling Mistakes / Special Characters

Definition:
Spelling or typing errors occur when text data (especially categorical data) has inconsistent spellings or in some cases insertion of special character like &,*,? etc...

Example:
“Hyderabad”, “Hydrabad”, “HYDERABAD” — all represent the same city but are treated as different categories.

"Hyd**", '???'.


#####  Wrong Labels/Attribute - Records mismatch.

Definition:
Incorrect labeling happens when a value is placed under the wrong category or a label is assigned wrongly.

Example:
In a gender column:
Male, Female, and mistakenly Manager.

Solution:

Verify with domain knowledge or reference lists

Correct manually or programmatically using mapping

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
loan = pd.read_csv('Updated_Loan.csv')
loan.head(1)

,Unnamed: 0,Loan_Status,Applicant_Income,Loan_Amount,Loan_Tenure,Gender,Dependents,Marriage_Status,Occupation,Credit_Score,DOB
0,0,Yes,674507.0,122980,15,Female,Yes,Yes,Business,Medium,1976

<a id='missing_values'></a>
#### Missing values

The missing data, or missing values, are values which occur when no data is stored for the variable in an observation. Understanding the concept of missing values is important in order to successfully manage data. Missing data often occur in data and needs to be handled properly. Improper handling may affect results obtained by the researcher.

In [71]:
df = pd.DataFrame({'Height':[np.nan,5.11,5.8,5.7,6.1,np.nan,np.nan,5.5],'Weight':[67,np.nan,87,91,np.nan,98,54,np.nan]})
df

   Height  Weight
0     NaN    67.0
1    5.11     NaN
2    5.80    87.0
3    5.70    91.0
4    6.10     NaN
5     NaN    98.0
6     NaN    54.0
7    5.50     NaN

##### Identifying Missing Values

##### Handling/treating missing values

##### Forward Fill

##### backward Fill

##### fillna

##### Mean Imputation

##### Median Imputation

##### Mode Imputation

##### Proportion Imputation

<a id="outliers"></a>
###  Outliers

An outlier is an observation in the data that lies at an abnormal distance from other values. Presence of an outlier may skew the results. Hence it is necessary to remove them.

### Identifying the Outliers

<a id="boxplot"></a>
####  Based on Boxplots/IQR Method:

The boxplot() in seaborn plots a box plot of the specified data. The box represents the quartiles of the data while the whiskers extend to show the rest of the distribution. The points that are determined to be outliers are identified using  the interquartile range (IQR) method.

In [1]:
import seaborn as sns 
import numpy as np
import pandas as pd

In [5]:
loan.head()

,Unnamed: 0,Loan_Status,Applicant_Income,Loan_Amount,Loan_Tenure,Gender,Dependents,Marriage_Status,Occupation,Credit_Score,DOB
0,0,Yes,674507.0,122980,15,Female,Yes,Yes,Business,Medium,1976
1,1,Yes,579260.0,111180,10,NaN,No,Yes,Job,High,1974
2,2,No,697153.0,93364,5,Male,Yes,No,Job,Medium,1990
3,3,Yes,828454.0,188090,5,Female,Yes,Yes,Job,High,1973
4,4,No,564876.0,92806,5,Female,Yes,Yes,Business,Low,1973

<a id="zscore"></a>
####  Based on Z-score

Z-score of a value is the difference between that value and the mean, divided by the standard deviation. If the z-score greater than 3 or less than -3, indicates an outlier value. This method is useful when the data distribution is normal. 

This method has a disadvantage that the values of mean and standard deviation are highly affected by the presence of outliers.

In [ ]:
#z_score = (x-mu)/sigma
x = loan['Applicant_Income']
mu = loan['Applicant_Income'].mean()
sigma = loan['Applicant_Income'].std()
loan['zscore_applicant_income'] = (x-mu)/sigma
loan[['Applicant_Income','zscore_applicant_income']].head(10)
right_side_outliers = loan[loan["zscore_applicant_income"]>3]
left_side_outliers =  loan[loan["zscore_applicant_income"]<3]

In [11]:
left_side_outliers.shape

(834, 12)

In [10]:
right_side_outliers.shape

(25, 12)

### Handling/Treating Outliers

##### Capping / Flooring (Winsorization):
Capping (or Winsorization) is a method where extreme outlier values are replaced by boundary (limit) values — instead of removing them completely.This keeps the data size the same but reduces the influence of extreme values.

##### Transformation Methods:
Transformation means applying a mathematical function to the data to reduce the effect of outliers and make the distribution more normal or symmetric.

In [6]:
loan['Occupation']

0      Business
1           Job
2           Job
3           Job
4      Business
         ...
995    Business
996         Job
997    Business
998         Job
999         Job
Name: Occupation, Length: 1000, dtype: object

##### Binning (Grouping Method): 
Binning converts continuous numerical data into categorical groups or intervals, which helps reduce the impact of extreme values.

##### Removal (Deletion Method):
This is the simplest technique, where rows containing outliers are removed from the dataset.

##### Separate Modeling (Keep Outliers):
Sometimes, outliers are genuine and meaningful observations (e.g.,Big Billion days, fraud cases, VIP customers, rare diseases). In such cases, instead of removing them, they are analyzed or modeled separately.

<a id="cat"> </a>
###  Encoding Techniques (Handle Non-Numeric Data)

The data may contain numerical as well as categorical variables. Machine learning algorithms are designed to work with numerical data.
Thus, it is necessary to convert the categorical variables into a numeric type. The process of converting Numerical data to Categorical data is called Encoding. Different techniques are available to perform such conversion.

##### Dummy Encoder :
Dummy Encoding is a technique that converts each category into a binary (0 or 1) column, but it drops one column to avoid multicollinearity (known as the dummy variable trap).

In [7]:
pd.get_dummies(loan['Occupation'],dtype='int').head(10)

   Business  Job
0         1    0
1         0    1
2         0    1
3         0    1
4         1    0
5         1    0
6         0    1
7         0    1
8         0    1
9         0    1

##### One Hot Encoder:
One-Hot Encoding converts each categorical value into a new binary column (0 or 1) for every unique category — no column is dropped.

##### Ordinal Encoder:
Ordinal Encoding assigns integer values to categories based on their order or ranking. Used when categories have a logical or natural order.

##### Label Encoder: 
Label Encoding converts each category into a unique numeric code (0, 1, 2, …) — without considering any order(follows alphabetical order).

##### Frequency Encoder:
Frequency Encoding replaces each category with the frequency or count of how often it appears in the dataset.

KeyError: "['credit_score_freq_enc'] not in index"

### Scaling

Scaling is the process of adjusting the range or magnitude of numerical features so that they are on a similar scale.
It ensures that no single feature dominates others due to large numerical differences.

In simple words —

Scaling brings all numerical values into a common range without changing the shape of the data distribution.

Many machine learning algorithms (like KNN, SVM, Gradient Descent, PCA) are distance-based or gradient-based.
If features have very different ranges (like Age in years and Salary in lakhs), models may give more weight to larger numbers.
Scaling solves this problem by normalizing or standardizing the values.

##### Types of Feature Scaling: There are several methods, but the two most common and widely used are:

##### Standardization (Standard Scaler): 
Standardization transforms the data so that it has a mean = 0 and a standard deviation = 1.
It centers the data around zero by removing the mean and scaling it to unit variance.

In [5]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
loan['Applicant_Income_SS'] = SS.fit_transform(loan[['Applicant_Income']])
np.round(loan['Applicant_Income_SS']).mean()
np.round(loan['Applicant_Income_SS']).std()

1.0194679852544346

##### Normalization (Min–Max Scaler): 
Normalization (also called Min–Max Scaling) transforms data to a fixed range, usually 0 to 1 (or sometimes –1 to 1).

In [9]:
from sklearn.preprocessing import MinMaxScaler
MM = MinMaxScaler()
loan['Applicant_Income_MM'] = MM.fit_transform(loan[['Applicant_Income']])
loan['Applicant_Income_MM'].describe()

count    859.000000
mean       0.096302
std        0.091195
min        0.000000
25%        0.061281
50%        0.081155
75%        0.100336
max        1.000000
Name: Applicant_Income_MM, dtype: float64

## Transformation: 
Data Transformation is the process of applying mathematical functions to change the scale, shape, or distribution of data values —
so that the data becomes more suitable for analysis or modeling.

It helps to:

Reduce skewness (make data more symmetric)

Handle outliers

Make data closer to a normal distribution

##### Log Transformation: 
Applies the natural logarithm (or log base 10) to reduce right skewness and compress large values. In general log values follow normal distribution.

##### Exponential Transformation: 
Applies an exponential function to each data value.
Used to reverse the effect of a log transform or to expand small differences.

##### Square Root Transformation: 
Takes the square root of each data value to reduce moderate skewness.

#### Power Transformers: 

##### Box-Cox Transformation: 
A specific type of power transformation that helps normalize non-normal data.
It can stabilize variance and reduce skewness — but only works for positive values

##### Yeo-Johnson Transformation:
An improved version of Box–Cox, which can handle zero and negative values as well.
It automatically finds the best λ (lambda) to make the data more normal.

### Feature Engineering

Feature Engineering is the process of creating, modifying, or transforming input variables (features) in a dataset to improve the performance of a machine learning model.

In simple words —

It’s the art of turning raw data into meaningful features that help a model learn patterns better.

#### Feature Creation (Deriving New Features)

Creating new features from existing ones that may provide additional insight to the model.

Examples:

From Date of Birth, derive Age

From Sales and Cost, derive Profit Margin = (Sales – Cost)/Sales

**Feature Transformation, Feature Scaling, Feature Encoding all these are some sort of Feature Engineering types.**